### ISSUE TITLE
pydantic schema?

### ISSUE THREAD

**Issue by magland** [rly/h5tojson#1]
I was thinking it would be useful to optionally provide the output as a pydantic object so that the format of the json could be self-documenting. This would also be very useful on the parsing side -- loading a .json file into the pydantic object. Further, this would make it easy (with the help of some AI) to convert the json loader to typescript/javascript. But I wasn't sure if you wanted to introduce the pydantic dependency. If you are willing to accept that dependency, I can take a crack at it. Otherwise, perhaps dataclasses is the way to go.

**Comment by rly** [comment]
Do you mean different Pydantic classes for each NWB data type, or generic Pydantic classes for groups and datasets? Either way, I think it's a good idea for more natural parsing. I am currently using `json.load` to parse the JSON into a generic dict in https://github.com/rly/h5tojson/blob/main/queries.ipynb This requires knowledge about the structure / guess-and-check, which is easy for me, but could be made even easier with Pydantic. 

Happy to have Pydantic as a dependency, and happy for you to take a crack at it!

**Comment by rly** [comment]
Resolved by #2
